repos:
- repo: local
  hooks:
  - id: check-changes
    name: Check CHANGES
    language: system
    entry: ./tools/check_changes.py
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
    exclude: rst$
- repo: https://github.com/asottile/yesqa
  rev: v1.4.0
  hooks:
  - id: yesqa
- repo: https://github.com/Zac-HD/shed
  rev: 0.10.7     # 0.7 does not support Python 3.7
  hooks:
  - id: shed
    args:
    - --refactor
    - --py37-plus
    types_or:
    - python
    - markdown
    - rst
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    alias: yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: [--remove]
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.22
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.19.2
  hooks:
  - id: check-github-actions
ci:
  skip:
  - actionlint-docker
  - check-github-actions
